database:
  user: root
  password: root
  name: nirun
  host: 127.0.0.1:3306

line_bot:
  lineAPIBaseURL: "https://api.line.me/bot/message/reply"
  # LINE_CHANNEL_SECRET: 2b5de1f896f32c5deb9cd1fed020e369
  # LINE_CHANNEL_ACCESS_TOKEN: wqxqI1WZYFANu8I/EJ5krYq/cAMT6/xr+msCJ2eDWzzHwragBCAt8Gy2Q/wvJX34Ayhphux2Xqg+xGgyHdbjbNVl6sbU7P7rB0hEI7XzzUweVkEcUik9EuycqhUQlpG4PlwgVjD7YyG5XcDDmTyzDwdB04t89/1O/w1cDnyilFU=
  webhook_url: "https://beb6-110-164-198-113.ngrok-free.app"
  LINE_CHANNEL_SECRET: 1d9aaa5b07131a52e6d541a277d6b3d7
  LINE_CHANNEL_ACCESS_TOKEN: s8wLcRhk8oxuHEN+rn5i23vAVrTPnXdZeE3FxupA2ztw48qb6zKCUeKhmafPfRlz89MFGM1lOVOVyKZlSmr6LCtioet1lUD7wxiV4sw/uuhnLcrYOiAmqHmSFHmjFjKbxYUcRUIFKFmsk8/oL6U51gdB04t89/1O/w1cDnyilFU=

agent:
  authtoken: 2oWauN3Vju6r1uXmOBz1fAtf2Lw_4LzvJNCvNJ73Yxv84rekw

minio:
  endpoint: localhost:9000
  accessKeyID: 5yQHqEAKvkKCQtXBOYxY
  secretAccessKey: S5ZWDrGTGLhe8YQn760OZR5gD2bvTbe7e1Qqkw78
  useSSL: false
  bucketName: nirunimages
